### ISSUE TITLE
Error message styling

### ISSUE THREAD

**Issue by Louisblack** [mkhackathon/redway-route-planner-2#15]
Server error is displayed on the front end now - either something went horribly wrong or the location wasn't found. At the moment it's just chucked on the screen within:

```<p class="error-message" ng-if="route.error">{{route.error}}</p>```

**Comment by LovegoodDigitalCreative** [comment]
Hey! How do I see this to edit it?

**Comment by Louisblack** [comment]
Sorry... only just seen this comment :/ If you put some random crap into the search field it should return an error.
