### ISSUE TITLE
Stop tracking user when they move around map, add resume button

### ISSUE THREAD

**Issue by Louisblack** [mkhackathon/redway-route-planner-2#3]
@LovegoodDigitalCreative Could you add a 'resume button' please? Something that the user can click to continue tracking them once they've finished moving around the map.

**Comment by Louisblack** [comment]
Added the code to do this.
I've just hacked in a basic icon with horrible CSS to act at the 'locate me' button, @LovegoodDigitalCreative can put in something a bit more permanent.

**Comment by LovegoodDigitalCreative** [comment]
Updated icon and added some background/spacing/positioning
