### ISSUE TITLE
App Icon

### ISSUE THREAD

**Issue by Louisblack** [mkhackathon/redway-route-planner-2#45]
Splitting this out from the description. The icon we can use into the development app build so it doesn't use the default PhoneGap icon on test devices. Whereas we only need description when submitting to App Store.

**Comment by LovegoodDigitalCreative** [comment]
![app-icon-itunesartwork](https://cloud.githubusercontent.com/assets/20873058/24677438/c0056130-197e-11e7-91c3-d14dffced931.png)
![app-icon 22x22](https://cloud.githubusercontent.com/assets/20873058/24677436/c003dd56-197e-11e7-8f71-a7f1231fdc83.png)
![app-icon 25x25](https://cloud.githubusercontent.com/assets/20873058/24677434/c0029aa4-197e-11e7-927d-b4bfef543250.png)
![app-icon 29x29](https://cloud.githubusercontent.com/assets/20873058/24677435/c003dfc2-197e-11e7-962f-77f993d13589.png)
![app-icon 44x44](https://cloud.githubusercontent.com/assets/20873058/24677437/c004c57c-197e-11e7-8139-a4fe5d980b30.png)
![app-icon 50x50](https://cloud.githubusercontent.com/assets/20873058/24677439/c0072b0a-197e-11e7-9ee2-6745b8c767a6.png)
![app-icon 58x58](https://cloud.githubusercontent.com/assets/20873058/24677441/c0154046-197e-11e7-97b8-0ebd97667f35.png)
![app-icon 60x60](https://cloud.githubusercontent.com/assets/20873058/24677440/c0152606-197e-11e7-82e9-f41526fe5bdd.png)
![app-icon 66x66](https://cloud.githubusercontent.com/assets/20873058/24677442/c01590e6-197e-11e7-88d0-a226a9bb4325.png)
![app-icon 75x75](https://cloud.githubusercontent.com/assets/20873058/24677445/c01b19bc-197e-11e7-809e-9f9a23917635.png)
![app-icon 76x76](https://cloud.githubusercontent.com/assets/20873058/24677443/c016a54e-197e-11e7-9c74-4e3a8a389449.png)
![app-icon 80x80](https://cloud.githubusercontent.com/assets/20873058/24677444/c0189638-197e-11e7-81f5-469c9f7e0f82.png)
![app-icon 87x87](https://cloud.githubusercontent.com/assets/20873058/24677446/c0263b12-197e-11e7-98cb-0ff2d24e8d83.png)
![app-icon 120x120](https://cloud.githubusercontent.com/assets/20873058/24677447/c0265296-197e-11e7-9c37-78fc7aa4c6a9.png)
![app-icon 152x152](https://cloud.githubusercontent.com/assets/20873058/24677449/c028e3ee-197e-11e7-9776-27e65afe1f36.png)
![app-icon 167x167](https://cloud.githubusercontent.com/assets/20873058/24677448/c028b32e-197e-11e7-8bc4-454006770f1b.png)
![app-icon 180x180](https://cloud.githubusercontent.com/assets/20873058/24677450/c029a202-197e-11e7-80fe-3a0f0821b99d.png)
